language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install coveralls
# command to run tests
script:
  - python test_tinydic.py
  - coverage run --source=home test_tinydic.py
after_success: coveralls
